# Generated by Django 6.0.6 on 2026-06-04 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('acres', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tree_count', models.IntegerField(default=0)),
                ('healthy', models.IntegerField(default=0)),
                ('needs_care', models.IntegerField(default=0)),
                ('needs_replacement', models.IntegerField(default=0)),
                ('canopy_coverage_pct', models.FloatField(default=0)),
                ('analysis_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='agrishield_app.farm')),
            ],
        ),
    ]
